repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [--profile=black, -s=backend/api/table/]
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: zsh -c 'cd dags && pytest'
        language: system
        files: ^dags/
        require_serial: true