# Generated by Django 5.0 on 2024-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=30, unique=True, verbose_name="아이디"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, null=True, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="닉네임"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, null=True, verbose_name="전화 번호"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
